---
- name: Deploy Website on Ubuntu
  hosts: web
  become: true
  vars:
    website_src: ./templatemo_520_highway/
    website_tmp_dest: /tmp/html
    website_final_dest: /var/www/html

  tasks:

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Enable and start Apache2
      systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Install rsync
      apt:
        name: rsync
        state: present

    - name: Ensure temporary web directory exists
      file:
        path: "{{ website_tmp_dest }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      become: false

    - name: Rsync website files to remote node under /tmp
      synchronize:
        src: "{{ website_src }}"
        dest: "{{ website_tmp_dest }}"
        recursive: yes
      delegate_to: localhost

    - name: Ensure final web root exists
      file:
        path: "{{ website_final_dest }}"
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Copy files from tmp to final web root
      shell: mv {{ website_tmp_dest }}/* {{ website_final_dest }}/
      args:
        executable: /bin/bash
      become: true

    - name: Set ownership to www-data for website files
      file:
        path: "{{ website_final_dest }}"
        owner: www-data
        group: www-data
        recurse: yes

