---
- name: Simple test playbook
  hosts: web
  gather_facts: yes

  tasks:
    - name: Ping the managed node
      ping:

    - name: Update APT cache
      apt:
        update_cache: yes
      become: true

    - name: Create a test file
      copy:
        dest: /tmp/jenkins_test_file.txt
        content: "Hello from Jenkins via Ansible!"
      become: true

